//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadTestDotNet
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;


    public class GetBlobCoded : WebTest
    {

        public GetBlobCoded()
        {
            this.Context.Add("StorageEndPoint", "http://dashjbtest.azurewebsites.net");
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            yield return GetRequest("Get Blob 1", "/anonymouscontainertest/test1.txt");
            yield return GetRequest("Get Blob 2", "/anonymouscontainertest/test2.txt");
        }

        WebTestRequest GetRequest(string reportingName, string path)
        {
            WebTestRequest request = new WebTestRequest((this.Context["StorageEndPoint"].ToString() + path));
            request.ReportingName = reportingName;
            request.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request.ExpectedHttpStatusCode = 200;
            request.Headers.Add(new WebTestRequestHeader("x-ms-version", "2014-02-14"));
            request.Headers.Add(new WebTestRequestHeader("x-ms-client-request-id", "adfb540e-1050-4c9b-a53a-be6cb71688d3"));

            return request;
        }
    }
}
